// Generated by SOS scripts/export-cloud-relay.cjs.
export function isValidPoint(point) {
    return Number.isFinite(point.latitude) && Math.abs(point.latitude) <= 90 &&
        Number.isFinite(point.longitude) && Math.abs(point.longitude) <= 180 &&
        Number.isFinite(point.measuredAt) && point.measuredAt > 0 &&
        (point.accuracy === null || (Number.isFinite(point.accuracy) && point.accuracy >= 0));
}
export function ageText(measuredAt, now = Date.now()) {
    const elapsed = now - measuredAt;
    if (!Number.isFinite(elapsed) || measuredAt <= 0 || elapsed < -60_000)
        return 'Время требует проверки';
    const minutes = Math.floor(Math.max(0, elapsed) / 60_000);
    if (minutes < 1)
        return 'Менее минуты назад';
    if (minutes < 60)
        return `${minutes} мин. назад`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24)
        return `${hours} ч. назад`;
    return new Date(measuredAt).toLocaleString('ru-RU');
}
export function pointText(point, now = Date.now()) {
    if (!point)
        return 'Местоположение ещё не получено';
    return `${point.latitude.toFixed(5)}, ${point.longitude.toFixed(5)}. ${ageText(point.measuredAt, now)}. ${accuracyText(point)}`;
}
export function accuracyText(point) {
    return point.accuracy === null ? 'Точность неизвестна' : `Точность около ${Math.ceil(point.accuracy)} м`;
}
export function wazeUrl(point) {
    if (!isValidPoint(point))
        throw new Error('Некорректные координаты');
    return `https://waze.com/ul?ll=${encodeURIComponent(`${point.latitude},${point.longitude}`)}&navigate=yes`;
}
export function shareText(name, point, demo) {
    return `${demo ? 'УЧЕБНАЯ ТОЧКА. Это не настоящее местоположение ребёнка.\n' : ''}${name}\nКоординаты: ${point.latitude.toFixed(5)}, ${point.longitude.toFixed(5)}\nОпределены: ${new Date(point.measuredAt).toLocaleString('ru-RU')}\n${accuracyText(point)}\n${wazeUrl(point)}`;
}
// Only location changes here. A GPS reply cannot make an old battery sample fresh.
export function applyPoint(children, id, point) {
    if (!isValidPoint(point))
        throw new Error('Некорректные координаты');
    return children.map(child => child.id === id && (!child.point || point.measuredAt >= child.point.measuredAt)
        ? { ...child, point } : child);
}
export function errorMessage(error) {
    if (error instanceof Error && error.message === 'offline')
        return 'Не удалось обновить. Телефон пока не ответил. Последняя точка сохранена.';
    if (error instanceof Error && error.message === 'timeout')
        return 'Ожидание закончилось. Свежие координаты не получены. Последняя точка сохранена.';
    return 'Не удалось получить местоположение. Попробуйте ещё раз.';
}
export class DemoTransport {
    delayMs;
    now;
    constructor(delayMs = 1200, now = () => Date.now()) { this.delayMs = delayMs; this.now = now; }
    async requestLocation(child, scenario, signal) {
        await new Promise((resolve, reject) => {
            if (signal.aborted) {
                reject(new Error('cancelled'));
                return;
            }
            const cancel = () => { clearTimeout(timer); reject(new Error('cancelled')); };
            const timer = setTimeout(() => { signal.removeEventListener('abort', cancel); resolve(); }, this.delayMs);
            signal.addEventListener('abort', cancel, { once: true });
        });
        if (signal.aborted)
            throw new Error('cancelled');
        if (scenario !== 'success')
            throw new Error(scenario);
        return {
            latitude: child.point?.latitude ?? 31.8,
            longitude: child.point?.longitude ?? 34.65,
            accuracy: 35,
            measuredAt: this.now(),
        };
    }
}
export function demoFamily(now = Date.now()) {
    return [
        { id: 'demo-katya', name: 'Катя', initial: 'К', color: '#E5E9FF', point: { latitude: 31.8000, longitude: 34.6500, accuracy: 35, measuredAt: now - 2 * 60_000 }, battery: { percent: 74, measuredAt: now - 2 * 60_000 } },
        { id: 'demo-sasha', name: 'Саша', initial: 'С', color: '#FBE9D6', point: { latitude: 31.8050, longitude: 34.6550, accuracy: 80, measuredAt: now - 24 * 60_000 }, battery: { percent: 42, measuredAt: now - 24 * 60_000 } },
    ];
}

