// Generated by SOS scripts/export-cloud-relay.cjs.
import { randomBytes } from 'node:crypto';
import { createServer } from 'node:http';
import { emptyFamily, seal, unseal } from './sos-protocol.js';
import { isValidPoint } from './sos-domain.js';
export class Relay {
    profiles;
    seen = new Map();
    samples = {};
    requests = [];
    lastSeen = {};
    revision = 0;
    now;
    constructor(profiles, now = Date.now) { this.profiles = new Map(profiles.map(p => [p.id, p])); this.now = now; }
    handle(envelope) {
        const now = this.now();
        const profile = this.profiles.get(envelope?.deviceId);
        if (!profile || profile.expiresAt <= now)
            throw new Error('unauthorized');
        const { command, sentAt } = unseal(profile, envelope, 'request');
        if (!Number.isFinite(sentAt) || Math.abs(now - sentAt) > 60_000)
            throw new Error('expired');
        for (const [id, expires] of this.seen)
            if (expires < now)
                this.seen.delete(id);
        const replayId = `${profile.id}:${envelope.requestId}`;
        if (this.seen.has(replayId) || this.seen.size > 20_000)
            throw new Error('replay');
        this.seen.set(replayId, now + 120_000);
        this.requests = this.requests.filter(r => r.expiresAt > now - 60_000);
        for (const r of this.requests)
            if (r.state === 'pending' && r.expiresAt <= now) {
                r.state = 'error';
                r.message = 'Телефон ребёнка не ответил вовремя. Последняя точка сохранена.';
            }
        this.lastSeen[profile.role === 'child' ? profile.childId : profile.name] = now;
        let reply;
        try {
            reply = this.dispatch(profile, command, now);
        }
        catch {
            reply = { snapshot: this.snapshot(profile), error: 'Команда отклонена. Проверьте подключение и повторите.' };
        }
        return seal(profile, envelope.requestId, 'response', reply, randomBytes);
    }
    snapshot(profile) {
        // Child credentials never reveal a sibling's position.
        const children = emptyFamily().filter(c => profile.role === 'parent' || c.id === profile.childId)
            .map(c => ({ ...c, point: this.samples[c.id]?.point ?? null, battery: this.samples[c.id]?.battery ?? null }));
        const ids = new Set(children.map(c => c.id));
        return { revision: ++this.revision, children, samples: Object.fromEntries(Object.entries(this.samples).filter(([id]) => ids.has(id))),
            requests: this.requests.filter(r => ids.has(r.childId)), lastSeen: Object.fromEntries(Object.entries(this.lastSeen).filter(([id]) => ids.has(id) || ['Папа', 'Мама'].includes(id))) };
    }
    dispatch(profile, command, now) {
        if (!command || typeof command !== 'object')
            throw new Error('command');
        let requestId;
        if (command.op === 'publish') {
            const { reading, sampleId } = command;
            if (profile.role !== 'child' || !reading || !reading.point || !isValidPoint(reading.point) ||
                reading.point.measuredAt > now + 60_000 || reading.point.measuredAt < now - 120_000 ||
                typeof sampleId !== 'string' || !/^[a-f0-9]{32}$/.test(sampleId))
                throw new Error('sample');
            const battery = reading.battery;
            if (battery !== null && (!battery || !Number.isInteger(battery.percent) || battery.percent < 0 || battery.percent > 100 ||
                !Number.isFinite(battery.measuredAt) || Math.abs(now - battery.measuredAt) > 120_000))
                throw new Error('battery');
            const req = command.requestId
                ? this.requests.find(r => r.id === command.requestId && r.childId === profile.childId)
                : this.requests.find(r => r.childId === profile.childId && r.state === 'pending' && r.expiresAt > now && reading.point.measuredAt >= r.expiresAt - 30_000);
            if (command.requestId && (!req || req.state !== 'pending' || req.expiresAt <= now || reading.point.measuredAt < req.expiresAt - 30_000))
                throw new Error('late');
            const old = this.samples[profile.childId];
            if (old && reading.point.measuredAt < old.point.measuredAt)
                throw new Error('stale');
            if (old?.id !== sampleId)
                this.samples[profile.childId] = { id: sampleId, point: { ...reading.point }, battery: battery ? { ...battery } : null, receipts: [] };
            if (req)
                req.state = 'done';
        }
        else if (command.op === 'request') {
            if (profile.role !== 'parent' || !emptyFamily().some(c => c.id === command.childId))
                throw new Error('role');
            let req = this.requests.find(r => r.childId === command.childId && r.state === 'pending');
            if (!req) {
                req = { id: randomBytes(16).toString('hex'), childId: command.childId, expiresAt: now + 30_000, state: 'pending' };
                this.requests.push(req);
            }
            requestId = req.id;
        }
        else if (command.op === 'ack') {
            if (profile.role !== 'parent')
                throw new Error('role');
            const sample = this.samples[command.childId];
            if (sample?.id === command.sampleId && !sample.receipts.includes(profile.name))
                sample.receipts.push(profile.name);
        }
        else if (command.op === 'failed') {
            if (profile.role !== 'child')
                throw new Error('role');
            const req = this.requests.find(r => r.id === command.requestId && r.childId === profile.childId && r.state === 'pending');
            if (req) {
                req.state = 'error';
                req.message = 'Телефон ребёнка не смог определить местоположение. Последняя точка сохранена.';
            }
        }
        else if (command.op !== 'poll')
            throw new Error('command');
        return { snapshot: this.snapshot(profile), ...(requestId ? { requestId } : {}) };
    }
}
export function createRelayServer(relay) {
    return createServer(createRelayHandler(relay));
}
export function createRelayHandler(relay, prefix = '', allowLocalBrowser = true) {
    return async (req, res) => {
        res.setHeader('Cache-Control', 'no-store');
        // Browser checks are local only; phones have no browser Origin header.
        const origin = req.headers.origin;
        if (origin && (!allowLocalBrowser || !/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(origin))) {
            res.writeHead(403);
            res.end();
            return;
        }
        if (origin) {
            res.setHeader('Access-Control-Allow-Origin', origin);
            res.setHeader('Vary', 'Origin');
        }
        if (req.method === 'OPTIONS') {
            res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
            res.setHeader('Access-Control-Allow-Methods', 'POST');
            res.writeHead(204);
            res.end();
            return;
        }
        if (req.url === `${prefix}/health` && req.method === 'GET') {
            res.end('SOS relay ready');
            return;
        }
        if (req.method !== 'POST' || req.url !== `${prefix}/exchange`) {
            res.writeHead(404);
            res.end();
            return;
        }
        try {
            let body = '', bytes = 0;
            for await (const chunk of req) {
                bytes += Buffer.byteLength(chunk);
                if (bytes > 65_536)
                    throw new Error('size');
                body += chunk.toString();
            }
            const result = relay.handle(JSON.parse(body));
            res.setHeader('Content-Type', 'application/json');
            res.end(JSON.stringify(result));
        }
        catch {
            res.writeHead(400);
            res.end('Connection rejected');
        }
    };
}

